package edu.weber.kadair.cs3270.cslearner;

/**
 * Created by Kenneth on 4/20/2016.
 */
public class DummyJson {
    public static String dummyJson = "{\"blogEntries\": [{\"blogEntryID\": 1,\"blogDate\": \"2015-10-10\",\"blogTitle\": \"Why I Love My Website\",\"blogText\": \"In the future I hope that I'll be able to update this website to have more server-side programming. I've taken a Scripting class at my University that focused on Perl, Python, and Bash. Additionally, I'm taking a Server-Side Web Development class right now that is focusing on PHP and MySQL. While I'm not 100% sure of the future of this website I'd really like to get a MySQL database and have at least some parts of the website made with PHP. Some ideas I've considered have been making a simple web forum or even making myself a blog database in which I could create a form to input a 'text' entry into a MySQL database which could then be used by PHP to automatically generate the HTML for each of the web pages. (Right now I manually code each of these blog entries so the last idea was particularly tempting.) We'll see what happens though. An amazing part of the computer science field is that there is nearly infinite information out there to learn which means there are nearly infinite possibilities for the projects that can be created.\"},\n" +
            "{\"blogEntryID\": 2,\"blogDate\": \"2015-10-09\",\"blogTitle\": \"Great now I want to be a hacker.\",\"blogText\": \"I'll be the first to admit I don't know a lot about security and hacking. I've seen a few videos about the anonymous hackers that used DDOS (Distributed Denial of Service) attacks against people they disagree with but beyond that I don't know a lot. However discovering that there is an entire distribution of Linux devoted to hacking and security blew my mind. While reading about Kali Linux I read a little about 'penetration' testing in which people can test security by attempting to hack their own systems. SO COOL!!! However, one comment in a video warned that attempting to hack anyone that hasn't agreed to it beforehand is multiple felonies which makes me a little paranoid to say the least.\"},\n" +
            "{\"blogEntryID\": 3,\"blogDate\": \"2015-12-20\",\"blogTitle\": \"CSLearner has been updated!  Server-side programming baby!\",\"blogText\": \"I've been thinking of updating the website for a long time. What finally created a window of opportunity that I couldn't ignore was in my university class we were allowed to pick our final project.  I decided to pitch my idea of updating my website which meant I could use class time to update my website.  After my project got approved I spent a few weeks working on it and was really excited when I thought it was done. I uploaded it to the live website and was frustrated when the website wasn't working the way it had been working on my test server.  (Coincidentally I use a virtual machine on VirtualBox as a test LAMP server before I usually upload anything to the live website.)  Because of this I took down the changes for a little bit and worked on the website more on my virtual machine until I felt it was ready.  Today is the day I uploaded the new website the second time and so far everything is going smoothly.\"}]}";

    public static CSLearnerObjects.blogEntries[] dummyJsonArray(){
        CSLearnerObjects.blogEntries one = new CSLearnerObjects.blogEntries(1, "2015-10-10", "Why I Love My Website", "In the future I hope that I'll be able to update this website to have more server-side programming. I've taken a Scripting class at my University that focused on Perl, Python, and Bash. Additionally, I'm taking a Server-Side Web Development class right now that is focusing on PHP and MySQL. While I'm not 100% sure of the future of this website I'd really like to get a MySQL database and have at least some parts of the website made with PHP. Some ideas I've considered have been making a simple web forum or even making myself a blog database in which I could create a form to input a 'text' entry into a MySQL database which could then be used by PHP to automatically generate the HTML for each of the web pages. (Right now I manually code each of these blog entries so the last idea was particularly tempting.) We'll see what happens though. An amazing part of the computer science field is that there is nearly infinite information out there to learn which means there are nearly infinite possibilities for the projects that can be created.");
        CSLearnerObjects.blogEntries two = new CSLearnerObjects.blogEntries(2, "2015-10-09", "Great now I want to be a hacker.", "I'll be the first to admit I don't know a lot about security and hacking. I've seen a few videos about the anonymous hackers that used DDOS (Distributed Denial of Service) attacks against people they disagree with but beyond that I don't know a lot. However discovering that there is an entire distribution of Linux devoted to hacking and security blew my mind. While reading about Kali Linux I read a little about 'penetration' testing in which people can test security by attempting to hack their own systems. SO COOL!!! However, one comment in a video warned that attempting to hack anyone that hasn't agreed to it beforehand is multiple felonies which makes me a little paranoid to say the least.");
        CSLearnerObjects.blogEntries three = new CSLearnerObjects.blogEntries(3, "2015-12-20", "CSLearner has been updated!  Server-side programming baby!", "I've been thinking of updating the website for a long time. What finally created a window of opportunity that I couldn't ignore was in my university class we were allowed to pick our final project.  I decided to pitch my idea of updating my website which meant I could use class time to update my website.  After my project got approved I spent a few weeks working on it and was really excited when I thought it was done. I uploaded it to the live website and was frustrated when the website wasn't working the way it had been working on my test server.  (Coincidentally I use a virtual machine on VirtualBox as a test LAMP server before I usually upload anything to the live website.)  Because of this I took down the changes for a little bit and worked on the website more on my virtual machine until I felt it was ready.  Today is the day I uploaded the new website the second time and so far everything is going smoothly.");
        CSLearnerObjects.blogEntries[] arr = new CSLearnerObjects.blogEntries[3];
        arr[0] = one;
        arr[1] = two;
        arr[2] = three;
        return arr;
    }
    /*protected class blogEntries{
        protected int blogEntryID;
        protected String blogDate;
        protected String blogTitle;
        protected String blogText;
    }*/

}
